#!/usr/bin/env ruby
$BOOTSTRAP_SCRIPT = <<EOF
# echo Running bootstrap script...
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.network :private_network, ip: "192.168.63.9"
  config.vm.provision :shell, privileged: false, :inline => $BOOTSTRAP_SCRIPT # see above
  config.ssh.forward_x11 = true
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  config.vbguest.auto_update = false

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--memory", 4196]
  end

  config.vm.define :unixpackageubuntu do |node|
    node.vm.box = "trusty64"
    node.vm.hostname = "ubuntu"
    node.vm.network :private_network, ip: "192.168.55.2"
  end
end

