#!/usr/bin/env ruby
$BOOTSTRAP_SCRIPT = <<EOF
# echo Running bootstrap script...
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/wily64"
#   config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/wily/current/wily-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.network :private_network, ip: "192.168.42.9"
  config.vm.provision :shell, privileged: false, :inline => $BOOTSTRAP_SCRIPT # see above
  config.ssh.forward_x11 = true
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  #config.vbguest.auto_update = false

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define :unixpackagewily do |node|
    node.vm.box = "trusty64"
    node.vm.hostname = "wily"
    node.vm.network :private_network, ip: "192.168.32.2"
  end
end

